import type { MiddlewareHandler } from "astro";

import { SECURITY_HEADERS } from "@mbele/config";

/**
 * Security headers on every server-rendered response. SECURITY.md §5.
 *
 * `public/_headers` covers what Cloudflare's asset handler serves — the stylesheet, the service
 * worker, the prerendered policy pages. It does NOT cover a response the Worker generates, and
 * almost every page in this product is generated by the Worker: the board, the opportunity pages,
 * the country matrix, the whole authenticated surface. Those were shipping with no CSP, no HSTS
 * and no Referrer-Policy, while a test that read `_headers` reported everything was in order.
 *
 * The values are not written here. They come from @mbele/config, which `_headers` is asserted
 * against — see apps/web/test/security-headers.test.ts.
 *
 * Existing headers are not overwritten: a route that deliberately sets its own Cache-Control or
 * Vary keeps it, and a route that has a reason to relax one of these can, visibly, in its own
 * file rather than by editing the global set.
 */
export const onRequest: MiddlewareHandler = async (_context, next) => {
  const response = await next();

  for (const [name, value] of Object.entries(SECURITY_HEADERS)) {
    if (!response.headers.has(name)) response.headers.set(name, value);
  }

  return response;
};
