#!/usr/bin/env node
/**
 * Embedding generation, locally. AI_SYSTEM.md §3.3 `[TD]`.
 *
 * "Embeddings are generated by `bge-small-en-v1.5` (384-dim) running LOCALLY INSIDE
 * GITHUB ACTIONS — free, unlimited, no rate limit, no vendor risk... This single
 * decision removes the largest potential quota consumer from the budget entirely.
 * Without it, embedding 8,000 opportunities plus 5,000 profiles plus re-embedding on
 * edits would exhaust every free API within days."
 *
 * §11's cost table bears that out: embeddings are ~500 calls/day against a total budget
 * of ~245 LLM calls/day for everything else. Paying for them would double the AI budget
 * for the least interesting part of the system.
 *
 * The model is q8-quantised ONNX, about 35 MB, cached by the runner between runs. It
 * loads in about a second and embeds a few hundred records a minute on a free runner,
 * which is comfortably more than a day's ingestion produces.
 *
 * Usage:
 *   DATABASE_URL=... node scripts/embed.mjs                 anything missing an embedding
 *   DATABASE_URL=... node scripts/embed.mjs --all           redo everything
 *   DATABASE_URL=... node scripts/embed.mjs --limit 200
 *   ... --dry-run
 */

import pg from "pg";

const args = process.argv.slice(2);
const ALL = args.includes("--all");
const DRY_RUN = args.includes("--dry-run");
const limitIndex = args.indexOf("--limit");
const LIMIT = limitIndex === -1 ? 500 : Number(args[limitIndex + 1] ?? 500);

const CONN = process.env.DATABASE_URL ?? process.env.SUPABASE_DB_URL;
if (!CONN) {
  console.error("Set DATABASE_URL for this command only (invariant 11).");
  process.exit(1);
}

/**
 * The model, as configuration rather than a hard-coded string — AI_SYSTEM.md §2
 * guardrail 6. The DIMENSION is not configuration: the column is halfvec(384) and a
 * model of another width would fail the insert, which is the right way for that mistake
 * to surface.
 */
const MODEL = process.env.EMBEDDING_MODEL ?? "Xenova/bge-small-en-v1.5";
const DIMENSIONS = 384;

const client = new pg.Client({
  connectionString: CONN,
  ssl: /supabase\.(co|com)/.test(CONN) ? { rejectUnauthorized: false } : false,
});

/**
 * What an opportunity is ABOUT, as text for the embedder.
 *
 * Deliberately not the whole description: a 4,000-word page embeds to a vector that
 * means "a web page about opportunities" rather than "a climate grant for Zimbabwean
 * undergraduates". Title, organisation, category, summary and tags are the fields that
 * carry the distinguishing signal, which is also the weighting §6.1 uses for full-text
 * search — so the two retrievers are looking at the same thing.
 *
 * @param {Record<string, any>} row
 */
function opportunityText(row) {
  return [
    row.title,
    row.organisation_name,
    row.category_name,
    row.summary,
    (row.tag_names ?? []).join(", "),
    row.eligibility_scope === "africa_wide" ? "open across Africa" : null,
    (row.eligible_countries ?? []).length > 0
      ? `open to ${(row.eligible_countries ?? []).join(", ")}`
      : null,
  ]
    .filter((part) => typeof part === "string" && part.trim() !== "")
    .join("\n")
    .slice(0, 2000);
}

/**
 * What a PERSON is about, from their PUBLIC profile only.
 *
 * AI_SYSTEM.md §8 and PRIVACY_AND_COMPLIANCE.md §2: the eligibility profile is never
 * embedded. Country of residence, birth year, student status and the rest are the
 * sensitive core, and a vector derived from them would be a derived copy of them
 * sitting in an index — searchable, and impossible to explain to the person it
 * describes. Matching uses the public profile, which the user wrote to be read.
 *
 * @param {Record<string, any>} row
 */
function profileText(row) {
  return [row.headline, row.bio, (row.open_to ?? []).join(", "), row.city, row.country_iso2]
    .filter((part) => typeof part === "string" && part.trim() !== "")
    .join("\n")
    .slice(0, 2000);
}

/** pgvector's text input format, shared by vector and halfvec. @param {number[]} values */
const toVectorLiteral = (values) => `[${values.map((v) => v.toFixed(6)).join(",")}]`;

await client.connect();
/** @type {Error | null} */
let failure = null;

try {
  const { rows: opportunities } = await client.query(
    `SELECT o.id, o.title, o.summary, o.eligibility_scope::text, o.eligible_countries,
            og.name AS organisation_name,
            c.name AS category_name,
            coalesce(ARRAY(SELECT t.name FROM tags t WHERE t.id = ANY (o.tag_ids)), '{}') AS tag_names
       FROM opportunities o
       LEFT JOIN organisations og ON og.id = o.organisation_id
       LEFT JOIN categories c ON c.id = o.category_id
      WHERE o.deleted_at IS NULL
        AND o.status IN ('published','in_review')
        AND ($1::boolean OR o.embedding IS NULL)
      ORDER BY o.published_at DESC NULLS LAST
      LIMIT $2`,
    [ALL, LIMIT],
  );

  const { rows: profiles } = await client.query(
    `SELECT p.user_id, p.headline, p.bio, p.open_to, p.city, p.country_iso2
       FROM profiles p
      WHERE ($1::boolean OR p.embedding IS NULL)
        AND (p.headline IS NOT NULL OR p.bio IS NOT NULL)
      LIMIT $2`,
    [ALL, LIMIT],
  );

  const work = [
    ...opportunities.map((row) => ({ kind: "opportunity", id: row.id, text: opportunityText(row) })),
    ...profiles.map((row) => ({ kind: "profile", id: row.user_id, text: profileText(row) })),
  ].filter((item) => item.text.trim() !== "");

  if (work.length === 0) {
    console.log("Nothing to embed.");
    process.exit(0);
  }

  console.log(`Embedding ${work.length} record(s) with ${MODEL} (local, free, unquota'd).`);

  const started = Date.now();
  const { pipeline } = await import("@huggingface/transformers");
  const extract = await pipeline("feature-extraction", MODEL, { dtype: "q8" });
  console.log(`  model loaded in ${((Date.now() - started) / 1000).toFixed(1)}s`);

  let written = 0;
  const BATCH = 16;

  for (let i = 0; i < work.length; i += BATCH) {
    const batch = work.slice(i, i + BATCH);
    // CLS pooling and L2 normalisation are what bge-small expects; cosine distance in
    // the index then reduces to a dot product, which is what makes the HNSW search
    // cheap.
    const output = await extract(
      batch.map((item) => item.text),
      { pooling: "cls", normalize: true },
    );

    const data = Array.from(output.data);
    for (let j = 0; j < batch.length; j += 1) {
      const vector = data.slice(j * DIMENSIONS, (j + 1) * DIMENSIONS);
      if (vector.length !== DIMENSIONS) {
        throw new Error(
          `${MODEL} produced ${vector.length} dimensions, not ${DIMENSIONS}. The column is halfvec(384); a model of another width needs a migration, not a cast.`,
        );
      }
      if (DRY_RUN) continue;

      const item = batch[j];
      if (item.kind === "opportunity") {
        await client.query("UPDATE opportunities SET embedding = $2::halfvec WHERE id = $1", [
          item.id,
          toVectorLiteral(vector),
        ]);
      } else {
        await client.query("UPDATE profiles SET embedding = $2::halfvec WHERE user_id = $1", [
          item.id,
          toVectorLiteral(vector),
        ]);
      }
      written += 1;
    }

    if ((i / BATCH) % 10 === 0 && i > 0) {
      console.log(`  ${i}/${work.length}…`);
    }
  }

  const seconds = (Date.now() - started) / 1000;
  console.log("");
  console.log(
    `Embedded ${written} record(s) in ${seconds.toFixed(1)}s ` +
      `(${(work.length / seconds).toFixed(1)}/s). No API was called.`,
  );
  if (DRY_RUN) console.log("(dry run — nothing was written)");
} catch (/** @type {any} */ err) {
  failure = err instanceof Error ? err : new Error(String(err));
} finally {
  await client.end();
}

if (failure) {
  console.error(`\nEmbedding failed: ${failure.message}`);
  // §13's failure matrix: "Embeddings stale -> Slightly worse ranking. FTS carries
  // retrieval." So this job failing is not an outage, and the exit code says "this run
  // did not work" rather than "the product is broken".
  console.error("Search still works: FTS carries retrieval when embeddings are stale (§13).");
  process.exit(1);
}
